CREATE TABLE public.otodom_houses
(
    number_id integer NOT NULL,
    short_id character varying(8) NOT NULL,
    long_id text NOT NULL,
    url text NOT NULL,
    title text NOT NULL,
    price integer NOT NULL,
    advertiser_type text,
    advert_type text,
    utc_created_at timestamp without time zone,
    utc_scraped_at timestamp without time zone,
    description text,
    city text,
    subregion text,
    province text,
    location text,
    latitude real,
    longitude real,
    market text,
    building_type text,
    house_features text,
    lot_area smallint,
    house_area smallint,
    n_rooms smallint,
    floors smallint,
    heating text,
    build_year smallint,
    media text,
    vicinity text,
    PRIMARY KEY (number_id)
);
